name: BlockEdit
version: ${project.version}
main: me.youhavetrouble.blockedit.BlockEdit
api-version: 1.19
authors: [ YouHaveTrouble ]
description: Modern WorldEdit alternative
website: https://youhavetrouble.me
