name: BlockEdit
version: ${project.version}
main: me.youhavetrouble.blockedit.BlockEdit
api-version: "1.20"
authors: [ YouHaveTrouble ]
description: Modern WorldEdit alternative
website: https://youhavetrouble.me
folia-supported: true
