name: Build plugin

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Drevision=BlockEdit-${{ github.ref_name }}-${{ github.sha::6 }}
      - name: Copy artifacts
        run: mkdir staging && cp target/BlockEdit-*.jar staging
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BlockEdit-${GITHUB_REF}-${GITHUB_SHA::6}
          path: staging